# Generated by Django 5.1.2 on 2024-12-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_genre_remove_film_cast_remove_film_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataApp.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataApp.film')),
            ],
        ),
    ]
