# Generated by Django 5.1.2 on 2024-12-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0004_film_filmimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='awards',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['institution_name']},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['event_title']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='musicalbum',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='occupations',
            options={'ordering': ['occupation_name']},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'ordering': ['quote_text']},
        ),
        migrations.AlterModelOptions(
            name='writtenworks',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='writtenworks',
            name='writtenWorksImage',
            field=models.ImageField(blank=True, null=True, upload_to='written_works/'),
        ),
    ]
